### ISSUE TITLE
Crash if no appimage path set

### ISSUE THREAD

**Issue by lluchs** [antony-jr/AppImageUpdaterBridge#15]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
If the check at https://github.com/antony-jr/AppImageUpdaterBridge/blob/20842724c749488cc5966160133c76498b5ba77b/src/AppImageUpdateInformation_p.cc#L485 is skipped (because Qt does not have any arguments), the code crashes at https://github.com/antony-jr/AppImageUpdaterBridge/blob/20842724c749488cc5966160133c76498b5ba77b/src/AppImageUpdateInformation_p.cc#L516

**Comment by antony-jr** [comment]
@lluchs Searching for that one for a long time(I assumed Qt must return at least the program name). I know the code is awful as of now but the new version is being developed on the refactor branch which should solve this and #16 , Thank you for your feed back. I will try to fix everything ASAP.

**Comment by antony-jr** [comment]
fixed in https://github.com/antony-jr/AppImageUpdaterBridge/commit/26a79d346dcd46db439df2113d9f8eb7ccb00236 , please wait until refactor merges into master.

**Comment by lluchs** [comment]
Thanks. I'm honestly not entirely sure what's happening there. The Qt documentation indeed seems to imply that there is at least one argument, but the implementation apparently doesn't enforce this. I reported this bug after observing the crash there in the debugger and seeing that you even have a check for "no arguments".

It's possible that in the end I'm somehow misusing Qt here. I'm trying to add automatic updates to a game that doesn't use Qt's mainloop, so the integration is slightly unusual. (Qt is already a dependency, so the library is a good fit otherwise.)

**Comment by antony-jr** [comment]
@lluchs Using Qt without the event loop ? But this library purely depends on the event loop. The single threaded and non-blocking API works because of Qt's event loop. If you want a pure C++ API then try the official one which does not depend on Qt's even loop and uses the standard C++ threads. And I think it only adds a little overhead to your application but using this without the event loop is not recommended.

**Comment by lluchs** [comment]
Qt actually supports external main loops and polling for events via `QCoreApplication::processEvents()`, so I think that part should actually be fine! We already use Qt widgets with that approach.

I looked into the official library shortly, but it requires a lot of extra dependencies, whereas this library is nicely self-contained.
