### ISSUE TITLE
#includes use brackets

### ISSUE THREAD

**Issue by lluchs** [antony-jr/AppImageUpdaterBridge#16]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

All the internal header files use `#include <somefile.hpp>` to include local files. This is problematic because it requires adding both `/path/to/AppImageUpdaterBridge` and `/path/to/AppImageUpdaterBridge/include` to the include path for users of the library. By using quotes instead (like `#include "somefile.hpp"`), the preprocessor will look for local files per default.

**Comment by antony-jr** [comment]
fixed this on https://github.com/antony-jr/AppImageUpdaterBridge/commit/79e92ddecdaf182d8dc0abae557997c70b315f88 , will be closed after merge. Thank you for reporting this.
