### ISSUE TITLE
Update error INVALID_ZSYNC_MTIME

### ISSUE THREAD

**Issue by lluchs** [antony-jr/AppImageUpdaterBridge#17]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Trying to update my AppImage with the example application or the API results in the `INVALID_ZSYNC_MTIME` error. I'm creating the AppImage with linuxdeployqt.

**Ways to Reproduce the issue (optional):**

```sh
# build SimpleUpdate
cd AppImageUpdaterBridge/examples/SimpleUpdate
qmake && make

# grab updateable AppImage
wget https://releases.openclonk.org/snapshots/2019-02-03T18:14:53Z-master-918c4139e/OpenClonk-x86_64.AppImage

# update fails with SimpleUpdate:
./SimpleUpdate OpenClonk-x86_64.AppImage
# SimpleUpdate , A Simple Updater using AppImageUpdaterBridge.
# Copyright (C) 2018 , Antony Jr.
# [                          ###                              ]      Revising New Version at 0.0   error::  AppImageUpdaterBridge::errorCode(INVALID_ZSYNC_MTIME)

# update works with appimageupdatetool:
wget https://github.com/AppImage/AppImageUpdate/releases/download/continuous/appimageupdatetool-x86_64.AppImage
chmod +x appimageupdatetool-x86_64.AppImage
./appimageupdatetool-x86_64.AppImage OpenClonk-x86_64.AppImage
# Checking for updates...
# ... done!
# Starting update...
# [...]
# Update successful. New file created: OpenClonk-x86_64.AppImage
```

**Comment by antony-jr** [comment]
@lluchs I will check on it ASAP , Possible that the zsync control file is corrupted or uses a new standard.

**Comment by antony-jr** [comment]
@lluchs Seems to work on my side , I got a Qt internal error though but I think I'm doing something tedious on direct zsync transport I will look into it. Are you sure that you are using the latest version ? 

```
SimpleUpdate , A Simple Updater using AppImageUpdaterBridge.
Copyright (C) 2018 , Antony Jr.
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once 

QUrl("https://releases.openclonk.org/snapshots/latest-master/OpenClonk-x86_64.AppImage.zsync")

[##########                       ] 63% Revising New Version at 456 kB/s.
```

More information can be helpful , like what version of the library are you using and what version of Qt?


**EDIT** : As I said I'm working on it in the refactor branch , it will be merging it today or tomorrow , So thanks for reporting this.

**EDIT**: I think I found the error , will be fixing it soon.

**Comment by lluchs** [comment]
I'm on Fedora 29. I think it's a locale issue. Try setting `LC_TIME=de_DE.UTF-8`. It works on my side if I set `LC_TIME=en_US.UTF-8`.

**Comment by antony-jr** [comment]
@lluchs Still a major bug exists , which should be fixed when refactor is merged. The current version thinks that your update server does not support range requests and thus it does not use the delta update. This is because the update server does not send the 'Accept-Ranges' header when partial content is requested but this has been fixed in the other branch. I will look into the locale.

**Comment by antony-jr** [comment]
@lluchs fixed this on https://github.com/antony-jr/AppImageUpdaterBridge/commit/79e92ddecdaf182d8dc0abae557997c70b315f88 , will be closed after merge.


**EDIT**:
```
QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once
```
is a new bug in Qt 5.12.1 which is fixed in Qt 5.12.2 so watch out for that.

**Comment by antony-jr** [comment]
@lluchs it should work fine with your AppImage. I have tested it already. Do report bugs in the future. Checkout the [documentation](https://antony-jr.github.io/AppImageUpdaterBridge/?reloadCache) (use private window if you see the old site because of browser cache.) for more information. 

**EDIT** : You don't need to change locale.

**Comment by antony-jr** [comment]
@lluchs is the library working on your side ? It should work even if the locale is different.

**Comment by antony-jr** [comment]
@lluchs you can try updating any appimage using this qt application which uses this library to do the update , https://github.com/antony-jr/AppImageUpdater ( Already tested with this and your appimage update was smooth.) (Run from terminal to see log messages which can give you insight on how the update process is done.)

**Comment by lluchs** [comment]
Thanks, I think it is working now with the example application. I was last stuck building the integration with our in-game UI and hope to continue next week.

**Comment by antony-jr** [comment]
@lluchs glad to hear that , by the way , played your game , **its awesome**.
