### ISSUE TITLE
Windows stay open even if I say "No" 

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdaterBridge#21]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

These windows stay open even if I say "No" when I am asked whether I want to update

![doesnotclose](https://user-images.githubusercontent.com/2480569/58905466-560a3900-86f9-11e9-99fc-982ddca4052e.png)
![needed](https://user-images.githubusercontent.com/2480569/58905467-56a2cf80-86f9-11e9-8694-646c5becf500.png)

**Comment by antony-jr** [comment]
Yes it looks terrible , Because its still under construction.

**Comment by antony-jr** [comment]
I'm currently trying to integrate this into the update check ,
![Screenshot_20190605_001820](https://user-images.githubusercontent.com/33930174/58905754-21fa3c80-8728-11e9-85f2-7b6ab26fdd08.png)

**Comment by probonopd** [comment]
Yes, this looks much, _much_, **_much_** better. Also, it looks very familiar to Mac users, which I like.

**Comment by antony-jr** [comment]
This should be fixed now. The new update dialog is integrated into [the example projects](https://github.com/TheFutureShell/updatedeployqt#projects-using-this), check it out. And also do you have better idea to notify the user that we are in the process of checking for updates?
