### ISSUE TITLE
Override existing menu entry

### ISSUE THREAD

**Issue by probonopd** [antony-jr/AppImageUpdaterBridge#22]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**

Some applications already have a "Check for updates" menu entry, e.g., here:

https://github.com/Subsurface-divelog/subsurface/blob/30f2d16dabd49ec0cb871f18ec1bb69f21478020/desktop-widgets/mainwindow.ui#L118-L126

It would be __awesome__ if we could override the existing one (or attach our functionality to it), not just add another menu entry.

**Comment by antony-jr** [comment]
Okay :+1: But please open issues in relevant repo. This will be transferred to updatedeployqt.

**Comment by probonopd** [comment]
I never know what is difference between AppImageUpdaterBridge, AppImageUpdaterBridgePlugin, updatedeployqt, and so on - wouldn't it be much easier to have everything in one repository?

**Comment by antony-jr** [comment]
> I never know what is difference between AppImageUpdaterBridge, AppImageUpdaterBridgePlugin, updatedeployqt, and so on - wouldn't it be much easier to have everything in one repository?

Well I deleted ,  AppImageUpdaterBridgePlugin in favor of the QtUpdateBridges repo.

updatedeployqt , does all the injection stuff.

AppImageUpdaterBridge , is just a Qt C++ library.

**Comment by probonopd** [comment]
Wouldn't it still be much easier to have everything in one repository? The advantage would be that if you make a change in any of those parts, everything would be rebuilt on Travis CI automatically. Same for pull requests. Much less work!

**Comment by antony-jr** [comment]
> Wouldn't it still be much easier to have everything in one repository?

No, I think everything is better this way. This library has no connection to updatedeployqt stuff or any other stuff which uses this. Some people or most of them use this as a standalone library(and updatedeployqt is just one of them). Projects like qTox always compiles libraries from source and never use prebuilt stuff. They even build appimagetool from source.

**Comment by probonopd** [comment]
I fail to see why using source rather than compiled stuff has something to do with how many source code repos to use...

**Comment by antony-jr** [comment]
In simple terms, I like everything decentralized. It just works this way. I don't see any benefits from combining everything under a single repo rather than more work.
