### ISSUE TITLE
True GPG support without using GPL licensed libraries

### ISSUE THREAD

**Issue by antony-jr** [antony-jr/AppImageUpdaterBridge#24]
**Select your issue type:** (check at least one)
- [ ] Bug
- [x] Question
- [x] Suggestion
- [x] Other (please describe):

**Describe your issue:**

Since a long time ago **AppImageUpdate** has used **sub-process** to use **gpg2 or gpg** programs to verify the GPG signature by writing the signature files and other required files to a temporary directory and passing on the command line. Now I did not implement this because I hate using sub-process but it is my last resort. So I propose that we re-implement the signature verification code for GPG in pure C++ and have support for event loops too so that both Qt and the official version can benefit. This has to be a header only library so that anyone can use it without any hassle.

**Comment by probonopd** [comment]
Since gpg is a security-critical component, I would not want to re-implement this. Let the gpg people care about their bugs ;-)

**Comment by antony-jr** [comment]
I don't know but I might re-invent it because I have [NIH Syndrome](https://en.wikipedia.org/wiki/Not_invented_here).
