### ISSUE TITLE
remove deprecated `register` keyword

### ISSUE THREAD

**Issue by technic** [antony-jr/AppImageUpdaterBridge#25]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:** AFAIK Nobody needs it in today's compilers and it is deprecated since C++11.

**Comment by antony-jr** [comment]
I'm currently doing all the changes in the experimental branch, I will close this once that branch is merged. Also I think you might be interested in this -> https://github.com/TheFutureShell/updatedeployqt

**Comment by antony-jr** [comment]
The latest commit(https://github.com/antony-jr/AppImageUpdaterBridge/commit/616234bfd963d4328d6ab71c1a4496c5995a659a) fixed this issue. You can check it your self by clicking on the following link, https://github.com/antony-jr/AppImageUpdaterBridge/search?q=register&unscoped_q=register
