### ISSUE TITLE
Static analyzer checks

### ISSUE THREAD

**Issue by technic** [antony-jr/AppImageUpdaterBridge#28]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
- `AutoBoolCounter` should probably be not copyable [link](https://technic93.gitlab.io/-/e2designer/-/jobs/340301712/artifacts/reports_html/appimageupdateinformation_p.cc_2820cb96f02541be7d4395f822edd343.plist.html#reportHash=e23a1ef46b1d11bc805f9c2d1a5f7af4), + there are some extra brackets in the same file.
- minor rounding issue [link](https://technic93.gitlab.io/-/e2designer/-/jobs/340301712/artifacts/reports_html/appimageupdaterdialog.cc_8d7005063164963a5bc9fe16a81dc6a2.plist.html#reportHash=bcb14c91f22394bfde8a1539965ab950) i.e. the integer division will never return non-integer megabytes.
- suspicious casts [link](https://technic93.gitlab.io/-/e2designer/-/jobs/340301712/artifacts/reports_html/zsyncwriter_p.cc_3fc19fd0f7881efe28a45dc543a71d43.plist.html#reportHash=c1e7722663e59d2748643f6b2b9cc859) don't know specific reasoning for this one :smile:

**Comment by technic** [comment]
Hi there is another pair of small issues from pvs studio analyzer
- https://github.com/antony-jr/AppImageUpdaterBridge/blob/master/src/zsyncwriter_p.cc#L776
Expression '!(constructed = true)' is always false.
- https://github.com/antony-jr/AppImageUpdaterBridge/blob/master/src/helpers_p.cc#L15 Expression is always false (QNetworkReply::UnknownNetworkError is 99)
- The possible overflows due to the cast were again reported

**Comment by probonopd** [comment]
pvs studio analyzer is amazing @technic

**Comment by technic** [comment]
@probonopd 
Yes, I am now trying to get nice reports from gitlab-ci

**Comment by antony-jr** [comment]
I'm a little busy right now, will look into it when I have more time.

**Comment by technic** [comment]
Ok, take your time. In case your are interested there is a [PVS analyzer log](https://technic93.gitlab.io/-/e2designer/-/jobs/389002709/artifacts/PVS-Studio.html/index.html)

**Comment by antony-jr** [comment]
We do have codacy for now(just a placeholder for PVS analyzer IMO).

**Comment by antony-jr** [comment]
@technic is there a way to get PVS license for free??

**Comment by technic** [comment]
@antony-jr Yes, they provide licenses for open source projects for free. However, there might be some additional limits or conditions https://www.viva64.com/en/b/0600/. You could send them an email and ask for it.

**Comment by antony-jr** [comment]
@technic Okay I think I got the free license. I tried with my protonmail but never got a license in the past(tried like 5 times). I created a gmail account just for this and I got the license in just few hours. PVS seems to hate secure mails.

I will integrate with PVS on v2.x

![pvs](https://user-images.githubusercontent.com/33930174/94248722-7a1c0a00-ff3c-11ea-956f-d72a641c1b80.png)

**Comment by technic** [comment]
@antony-jr Great! But this issue is not about PVS integration, rather it's about fixing those few points where the analyzer throws warnings.

**Comment by antony-jr** [comment]
> @antony-jr Great! But this issue is not about PVS integration, rather it's about fixing those few points where the analyzer throws warnings.

Actually some of them are intentional as to show off C idioms in the code. But I think readability is important than language idioms.

**Comment by antony-jr** [comment]
I will try to fix all warnings and errors given by PVS when I have time. Now you can see the analysis on each commit from the documentation itself. [Documentation Link](https://antony-jr.github.io/QAppImageUpdate)

![pvs](https://user-images.githubusercontent.com/33930174/97460331-a9ba9980-1962-11eb-8918-c8e07856bdaa.png)
