### ISSUE TITLE
Request for Ownership transfer

### ISSUE THREAD

**Issue by antony-jr** [antony-jr/AppImageUpdaterBridge#5]
Hey @probonopd , I think this is a perfect time to **transfer ownership** to **AppImage** organization , What do you think ? Once you have the ownership , you can **change the name** or do anything with the project but don't worry since I will maintain it **if you like**. ❤️ 😄

**Comment by probonopd** [comment]
Hi @antony-jr thank you for your offer to maintain AppImageUpdaterBridge inside the AppImage organization. I will discuss this move with other project contributors. Are you aware that making it "official", it would mean that you wold need to follow some rules set by the AppImage project, e.g., UX decisions?

**Comment by antony-jr** [comment]
no problem as this is a library , UX is upto you. I'm currently experimenting with **static qt builds** , the good part is that , when I build **static version** of the **test app** , it only takes less than **8 MiB** , with optimization , near to **5 MiB**. ( lighter than **FLTK** )

❤️ Excited about how well I can optimize **Qt**. According to the **docs** , with optimization **Qt** can fit into **4.7 MiB** with all its functionalities , even **networking**. ( i.e with **UPX** , and AppImage compress it even more ). Might give a path to create **Self-Updaters** for users with little overhead as **4 MiB**. ( with **0 %** of **Programming** by the application author )

**Comment by probonopd** [comment]
Static builds are not an option for us due to Qt licensing. And Qt sizes are not an issue for AppImageUpdaterBridge, since Qt applications are already bundling Qt anyway.

**Comment by antony-jr** [comment]
The users will only use a binary which is **LGPL** licensed so the users don't really have to release their source , only we have to release the source ( Which is not a problem ) , its like copying **ImageEditor** into your **AppImage** and using it to edit images from your main app (which is output by the program and thus its no problem).  Using a LGPL licensed binary by subprocess in our **MainApp** (which is MIT licensed), count as voilation ( no , as stated by LGPL ).

>  For the purpose of complying with the LGPL (any extant version: v2, v2.1 or v3):
>  (1) If you statically link against an LGPL'd library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.

That states it pretty clear.

**From FAQ**:
**Is there some way that I can GPL the output people get from use of my program? For example, if my program is used to develop hardware designs, can I require that these designs must be free?**
 
> In general this is legally impossible; copyright law does not give you any say in the use of the output people make from their data using your program. If the user uses your program to enter or convert her own data, the copyright on the output belongs to her, not you. More generally, when a program translates its input into some other form, the copyright status of the output inherits that of the input it was generated from.

**The Self-Updater is just manipulating data , just invoked by a user.**

But I'm not entirely sure about this , More insight is needed.

**Comment by antony-jr** [comment]
The **Self-Updater** is just an option.

**Comment by probonopd** [comment]
In any case, the main application will bundle Qt anyways, so what is the point?

**Comment by antony-jr** [comment]
well if its just a single **executable** which is **less than 4.7 MiB** ( **1.6** MiB on a single QMainWindow application with networking Without AppImage Compression ). A Overhead of **1.6** MiB is nothing (with AppImage compression , it will be **800 KiB** ) . Also offerring **0 %** Programming. ( We don't need to bundle any Qt Libs )

**Use Cases**:
> As a Application Author , I just want to implement an AutoUpdater with a single command on my continous build with little overhead as 2 MiB or less.
``` cp -p AppImageSelfUpdater ./appdir/usr/bin/ ```

### How to Setup AutoUpdate for your AppImages ?
**Step 1:** Copy **AppImageSelfUpdater** to your appdir/bin.
**Step 2:** Copy your **MainApp** and Point the AppRun to the **AppImageSelfUpdater**. 
**Step 3:** Bundle your App.
Thats it.

This solves https://github.com/AppImage/AppImageUpdate/issues/30 , https://github.com/AppImage/AppImageKit/issues/133.

I will build this as an open source project , If you like it then recommend your users to give a try. ( **Totally Optional**  )

**Comment by probonopd** [comment]
@antony-jr again the question: Since the main application (payload application, e.g., Subsurface) will bundle Qt anyways, why should one bother with statically linking?

**Comment by antony-jr** [comment]
well you can also link it dynamically ( Exceptions for Qt Projects ) (**800** KiB for using the existing shared libs and **3.3 MiB** for  using the standalone static version ) , This is also a condition in the **LGPL**. 

The general idea is to create something like this , without modifying the **AppRun**.

> Current AppImages can be updated via an external tool, AppImageUpdate. I wonder if AppImageUpdate's heuristic could be embedded in the AppImage itself. For example, a given AppImage's AppRun could check for updates, and ask user to download them if available, before spawning the application itself.

The user is free to use **AppImageUpdaterBridge** for Qt Projects too...

**Comment by probonopd** [comment]
Ah, you are talking about a standalone version similar to AppImageUpdate. I see.

**Comment by antony-jr** [comment]
@probonopd Please see that , **AppImageUpdaterBridge** is **documented** with https://docusaurus.io/ , So no need for documentations elsewhere. When you change the ownership , Please check the information carefully , I can help you with the transition of the documention , **Docusaurus** also has support for multi-language ( Built by **Facebook OpenSource** ).

**Comment by probonopd** [comment]
So https://docusaurus.io/ was used to produce https://antony-jr.github.io/AppImageUpdaterBridge/? Interesting, I'd like to learn more about it, and maybe use it for all of AppImage. How can I add, for example, German?

**Comment by antony-jr** [comment]
Here is an example on transalations using crowdin ( used by **Github**  and other major platforms ) , https://docusaurus.io/docs/en/translation.html

> Docusaurus itself does not do any translation from one language to another. Instead, it integrates Crowdin to upload translations and then downloads the appropriately translated files from Crowdin.

**Ref:** [Crowdin](https://crowdin.com/) ( Login with **GitHub** )

**Comment by antony-jr** [comment]
with this you do not have to do the **transalation** manually. **Docusaurus** also provides a **Blog** and lot of other goodies.  ( I use docusaurus for all my projects , it makes the docs attractive and thus makes it easier to read ) , Who does not like a good documentation.

**Comment by antony-jr** [comment]
**NOTE** : You need to request a free academic license for AppImage ( Crowdin is free for opensource projects ) https://crowdin.com/page/open-source-project-setup-request

**From Crowdin:**
**Before submitting this form, please ensure your project meets the following criteria:**

    You have created translation project in Crowdin.
    The project is licensed under an approved license from the Open Source Initiative.
    Your project source code is available for download to the public.
    You do not have Commercial products related to the Open Source project   
    you are requesting a license for
    You are the project lead.
    You have been working on your open source project for at least 3 months.
    You have an active community of collaborators.
    You keep the News section on your site up to date.
    You release updated builds on a regular basis.

**Comment by antony-jr** [comment]
Hey @TheAssassin , What do you think about taking this repo inside **AppImage** , as the issue states. 

>  I think this is a perfect time to transfer ownership to AppImage organization , What do you think ? Once you have the ownership , you can change the name or do anything with the project but don't worry since I will maintain it if you like. ❤️ 😄

As I mentioned in IRC , This project is not a competetion but just a pure Qt implementation for the official AppImageUpdate library. As you said that the official library ( in stable release ) will be in standard C++ , right ? 

Please see that C++ Callbacks and **Qt** signals and slots are very different. You **can** use **standard** C++ Callbacks in **GTK+** , **FLTK** and other **GUI Toolkits** but not efficiently in **Qt**. And thats when this library steps in for Qt Developers.

from **Qt Docs** ,

> Callbacks have two fundamental flaws: Firstly, they are not type-safe. We can never be certain that the processing function will call the callback with the correct arguments. Secondly, the callback is strongly coupled to the processing function since the processing function must know which callback to call.

> Compared to callbacks, signals and slots are slightly slower because of the increased flexibility they provide

The speed probably doesn't matter for most cases, but there may be some extreme cases of repeated calling that makes a difference. 

And another reason for this implementation is that , We don't really need any third party libraries for the operations like downloading files and other stuff. ( Not even curl ). Also note that **P2P** can also be implemented in Qt anytime without complexities. 
The best part is , **QtCore** libs covers this all and only takes arround 800 **KiB** if stripped. ( But size does not matter for Qt Devs ) , In the near future , I will be rewritting **zsync** with **P2P** ( a while later though ) in Qt with **signals** and **slots** which makes it even more faster and smoother for later development.

**So whats on your Mind ?** Please do see that you can change the copyright license too...

**Comment by antony-jr** [comment]
I think its wise to keep this as an unofficial API for Qt Only. Thank you for your Time! ⏲ 👍 ❤️
