### ISSUE TITLE
Consider using QCommandLineParser

### ISSUE THREAD

**Issue by technic** [antony-jr/AppImageUpdaterBridge#8]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Minor code style comment:
Consider using [QCommandLineParser](http://doc.qt.io/qt-5/qcommandlineparser.html) instead of manual `argc`, `**argv` manipulation.

**Comment by antony-jr** [comment]
Some reference would be nice , If its the examples just avoid it since its just an example , or feel free to give a PR on changing the example. Its not really a big deal since we are not teaching anyone Qt , We just need to show an example on how to use the library and that does the job.

**Comment by probonopd** [comment]
It is always a good idea to follow best practices but unfortunately I am not enough of a Qt expert to give useful input here.

**Comment by antony-jr** [comment]
Well its not really much of a work , So I think I can do that nitpick if I have some time.
