### ISSUE TITLE
Consider avoiding macros

### ISSUE THREAD

**Issue by technic** [antony-jr/AppImageUpdaterBridge#9]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [x] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
Hi,
These are another codestyle suggestions:

THREAD_SAFE_AREA macro is really ugly, why not to use QMutexLocker? Do we really need always tryLock? Anyway RAII can do the job in both cases.

CONSTRUCT() macros is also very strange, why don't you use just a function?

**Ways to Reproduce the issue (optional):**
Look into the sources :-)

**Comment by technic** [comment]
Also if we require for Qt >= 5.10 there is a nice way to replace `QUEUED_CALL_FUNC*` macroses:
with [QMetaObject::invokeMethod](http://doc.qt.io/qt-5/qmetaobject.html#invokeMethod-5):
```c++
QMetaObject::invokeMethod(obj, []{ ... });
```

**Comment by antony-jr** [comment]
@technic We can replace ```QUEUED_CALL_FUNC``` macros but why other macros such as ```CONSTRUCT``` and ```THREAD_SAFE_AREA``` , I used those since macros are faster and if we use a function it would complicate things(you have to create three different functions for each construct which we can just do that in separate constructors , Thus only a macro is perfect for this job , don't you think ? ).

Maybe I will think about it , Its just a matter of copy and paste which is done by the compiler on compilation , I just hate repeating code.

**Comment by technic** [comment]
Regarding `CONSTRUCT()`, you can call some private function from the constructor, that would do all those `connect(...)` calls.

**Comment by antony-jr** [comment]
@technic I think we need to support Qt versions less than 5.10 too , So I think we cannot use ``` QMetaObject::invokeMethod```.

**Comment by technic** [comment]
There is another option to use new c++11 signal/slot syntax:
```cpp
QTimer::singleShot(0, _pDeltaRevisioner, []{ ... });
```

**Comment by antony-jr** [comment]
@technic I've reduced the use of macro's drastically on https://github.com/antony-jr/AppImageUpdaterBridge/commit/79e92ddecdaf182d8dc0abae557997c70b315f88 , this will be closed after merge.

**Comment by technic** [comment]
I don't see it in those commit, but anyway it was a big refactoring :) 
If you want my opinion I think the code is much cleaner now.
BTW I think your `getMethod` function cat take just `QObject*` as a first argument.

**Comment by antony-jr** [comment]
>  BTW I think your `getMethod` function cat take just `QObject*` as a first argument.

@technic I've made that change too in a recent commit.
